// Peptide reconstitution defaults — edit this list to add or adjust peptides.
// Fields: vial (mg or IU), water (ml), dose (number), doseUnit ('mg'|'mcg'|'iu'), syringe (units/ml).
// Loaded before app.js so PEPTIDE_DEFAULTS is available globally.

var PEPTIDE_DEFAULTS = {
  'BPC-157':           { vial: 5,  water: 2.0, dose: 0.25, doseUnit: 'mg', syringe: 100 },
  'TB-500':            { vial: 5,  water: 2.0, dose: 2,    doseUnit: 'mg', syringe: 100 },
  'GHK-Cu':            { vial: 50, water: 3.0, dose: 2,    doseUnit: 'mg', syringe: 100 },
  'KPV':               { vial: 5,  water: 2.0, dose: 0.5,  doseUnit: 'mg', syringe: 100 },
  'CJC-1295 DAC':      { vial: 2,  water: 2.0, dose: 1,    doseUnit: 'mg', syringe: 100 },
  'Ipamorelin':        { vial: 5,  water: 2.0, dose: 0.3,  doseUnit: 'mg', syringe: 100 },
  'Sermorelin':        { vial: 5,  water: 2.0, dose: 0.3,  doseUnit: 'mg', syringe: 100 },
  'Tesamorelin':       { vial: 5,  water: 2.0, dose: 2,    doseUnit: 'mg', syringe: 100 },
  'Hexarelin':         { vial: 5,  water: 2.0, dose: 0.1,  doseUnit: 'mg', syringe: 100 },
  'GHRP-2':            { vial: 5,  water: 2.0, dose: 0.2,  doseUnit: 'mg', syringe: 100 },
  'GHRP-6':            { vial: 5,  water: 2.0, dose: 0.2,  doseUnit: 'mg', syringe: 100 },
  'MOTS-c':            { vial: 10, water: 2.0, dose: 10,   doseUnit: 'mg', syringe: 100 },
  'Epithalon':         { vial: 10, water: 2.0, dose: 10,   doseUnit: 'mg', syringe: 100 },
  'Selank':            { vial: 5,  water: 2.0, dose: 0.25, doseUnit: 'mg', syringe: 100 },
  'Semax':             { vial: 5,  water: 2.0, dose: 0.25, doseUnit: 'mg', syringe: 100 },
  'Semaglutide':       { vial: 5,  water: 2.0, dose: 0.5,  doseUnit: 'mg', syringe: 100 },
  'Tirzepatide':       { vial: 10, water: 2.0, dose: 5,    doseUnit: 'mg', syringe: 100 },
  'Retatrutide':       { vial: 10, water: 2.0, dose: 4,    doseUnit: 'mg', syringe: 100 },
  'Cagrilintide':      { vial: 5,  water: 2.0, dose: 1,    doseUnit: 'mg', syringe: 100 },
  'Liraglutide':       { vial: 15, water: 3.0, dose: 2,    doseUnit: 'mg', syringe: 100 },
  'PT-141':            { vial: 10, water: 2.0, dose: 1,    doseUnit: 'mg', syringe: 100 },
  'Melanotan 2':       { vial: 10, water: 2.0, dose: 0.5,  doseUnit: 'mg', syringe: 100 },
  'Oxytocin':          { vial: 2,  water: 2.0, dose: 0.05, doseUnit: 'mg', syringe: 100 },
  'LL-37':             { vial: 5,  water: 2.0, dose: 0.5,  doseUnit: 'mg', syringe: 100 },
  'Thymosin Alpha-1':  { vial: 5,  water: 2.0, dose: 1.6,  doseUnit: 'mg', syringe: 100 },
  'Thymalin':          { vial: 10, water: 2.0, dose: 10,   doseUnit: 'mg', syringe: 100 },
  'IGF-1 LR3':         { vial: 1,  water: 1.0, dose: 0.05, doseUnit: 'mg', syringe: 100 },
  'IGF-1 DES':         { vial: 1,  water: 1.0, dose: 0.1,  doseUnit: 'mg', syringe: 100 },
  'MGF (C-terminal)':  { vial: 2,  water: 2.0, dose: 0.2,  doseUnit: 'mg', syringe: 100 },
  'PEG-MGF':           { vial: 2,  water: 2.0, dose: 0.2,  doseUnit: 'mg', syringe: 100 },
  'HGH Fragment 176-191': { vial: 5, water: 2.0, dose: 0.5,  doseUnit: 'mg', syringe: 100 },
  'AOD9604':           { vial: 5,  water: 2.0, dose: 0.3,  doseUnit: 'mg', syringe: 100 },
  'SS-31':             { vial: 5,  water: 2.0, dose: 5,    doseUnit: 'mg', syringe: 100 },
  'FOXO4-DRI':         { vial: 5,  water: 2.0, dose: 5,    doseUnit: 'mg', syringe: 100 },
  'NAD+':              { vial: 50, water: 2.0, dose: 50,   doseUnit: 'mg', syringe: 100 },
  'Glutathione':       { vial: 50, water: 2.0, dose: 50,   doseUnit: 'mg', syringe: 100 },
  'DSIP':              { vial: 5,  water: 2.0, dose: 0.25, doseUnit: 'mg', syringe: 100 },
  'Kisspeptin-10':     { vial: 5,  water: 2.0, dose: 0.1,  doseUnit: 'mg', syringe: 100 },
  'Gonadorelin':       { vial: 10, water: 2.0, dose: 0.1,  doseUnit: 'mg', syringe: 100 },
  'GHRH':              { vial: 5,  water: 2.0, dose: 0.1,  doseUnit: 'mg', syringe: 100 },
  'ModGRF 1-29':       { vial: 5,  water: 2.0, dose: 0.1,  doseUnit: 'mg', syringe: 100 },
  'Follistatin-315':   { vial: 1,  water: 2.0, dose: 0.1,  doseUnit: 'mg', syringe: 100 },
  'Follistatin-344':   { vial: 1,  water: 2.0, dose: 0.1,  doseUnit: 'mg', syringe: 100 },
  'HGH (Somatropin)':  { vial: 10, water: 1.0, dose: 2,    doseUnit: 'iu', syringe: 100 }
};
